"""
Default floor plan data constants.

This module contains default room configurations, door placements,
window placements, and other floor plan elements used when no YAML
configuration file is available.
"""

# =============================================================================
# MAIN FLOOR DEFAULT DATA
# =============================================================================

MAIN_FLOOR_ROOMS_DEFAULT = [
    # Garage area
    {
        "x": 45,
        "y": 81,
        "width": 25,
        "height": 29,
        "label": "2 Car Garage",
        "color": "garage",
        "label_fontsize": 10,
        "auto_dimension": True,
        "dimension_text": "29'-2\" x 31'-9\"",
    },
    {
        "x": 55,
        "y": 70,
        "width": 8,
        "height": 11,
        "label": "Mud Room",
        "color": "utility",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "11' x 7.5'",
    },
    # Bedrooms
    {
        "x": 58,
        "y": 56,
        "width": 12,
        "height": 14,
        "label": "Bedroom 3",
        "color": "bedroom",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "13' x 13'",
    },
    {
        "x": 63,
        "y": 48,
        "width": 7,
        "height": 8,
        "label": "Bath 3",
        "color": "bathroom",
        "label_fontsize": 8,
    },
    {
        "x": 58,
        "y": 48,
        "width": 5,
        "height": 8,
        "label": "WIC",
        "color": "closet",
        "label_fontsize": 7,
    },
    {
        "x": 58,
        "y": 33,
        "width": 12,
        "height": 15,
        "label": "Bedroom 2",
        "color": "bedroom",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "14' x 14.5'",
    },
    {
        "x": 58,
        "y": 23,
        "width": 12,
        "height": 10,
        "label": "Bath 2",
        "color": "bathroom",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "11'4\" x 11'",
    },
    {
        "x": 53,
        "y": 40,
        "width": 5,
        "height": 8,
        "label": "WIC",
        "color": "closet",
        "label_fontsize": 7,
    },
    {
        "x": 50,
        "y": 60,
        "width": 8,
        "height": 10,
        "label": "Laundry",
        "color": "utility",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "12'",
    },
    # Kitchen area
    {
        "x": 45,
        "y": 19,
        "width": 13,
        "height": 14,
        "label": "Breakfast\nNook",
        "color": "kitchen",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "14' x 14'",
    },
    {
        "x": 40,
        "y": 68,
        "width": 15,
        "height": 13,
        "label": "Bedroom 4",
        "color": "bedroom",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "13' x 13'",
    },
    {
        "x": 45,
        "y": 60,
        "width": 10,
        "height": 8,
        "label": "Bath 4\nWIC",
        "color": "bathroom",
        "label_fontsize": 8,
    },
    {
        "x": 45,
        "y": 52,
        "width": 10,
        "height": 8,
        "label": "Pantry",
        "color": "utility",
        "label_fontsize": 7,
    },
    # Middle section
    {
        "x": 38,
        "y": 37,
        "width": 15,
        "height": 15,
        "label": "Kitchen",
        "color": "kitchen",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "13' x 12'",
    },
    {
        "x": 32,
        "y": 52,
        "width": 13,
        "height": 16,
        "label": "Butler's\nPantry",
        "color": "kitchen",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "15' x 8'",
    },
    {
        "x": 38,
        "y": 5,
        "width": 15,
        "height": 14,
        "label": "Breakfast\nPorch",
        "color": "porch",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "13'4\" x 12'",
    },
    {
        "x": 20,
        "y": 19,
        "width": 18,
        "height": 18,
        "label": "Family Room",
        "color": "living",
        "label_fontsize": 10,
        "auto_dimension": True,
        "dimension_text": "16'6\" x 15'-2\"",
        "notes": "Vaulted Clg.",
    },
    {
        "x": 22,
        "y": 63,
        "width": 18,
        "height": 18,
        "label": "Dining\nRoom",
        "color": "dining",
        "label_fontsize": 10,
        "auto_dimension": True,
        "dimension_text": "18' x 14'6\"",
    },
    {
        "x": 22,
        "y": 51,
        "width": 10,
        "height": 12,
        "label": "Front\nHall",
        "color": "hall",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "10'-2\" x 12'",
    },
    {
        "x": 8,
        "y": 70,
        "width": 14,
        "height": 11,
        "label": "Foyer",
        "color": "hall",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "11' x 13'",
    },
    {
        "x": 20,
        "y": 5,
        "width": 18,
        "height": 14,
        "label": "Outdoor\nLiving",
        "color": "porch",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "35'-2\" x 13'",
    },
    # Master suite area
    {
        "x": -4,
        "y": 67,
        "width": 12,
        "height": 14,
        "label": "Lounge",
        "color": "living",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "14'-2\" x 12'-2\"",
    },
    {
        "x": 8,
        "y": 53,
        "width": 14,
        "height": 14,
        "label": "Bar",
        "color": "living",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "14'6\" x 9'4\"",
    },
    {
        "x": 8,
        "y": 45,
        "width": 7,
        "height": 8,
        "label": "WIC",
        "color": "closet",
        "label_fontsize": 7,
        "auto_dimension": True,
        "dimension_text": "12'",
    },
    {
        "x": 8,
        "y": 32,
        "width": 12,
        "height": 13,
        "label": "Office",
        "color": "office",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "12'6\" x 12'",
    },
    {
        "x": 8,
        "y": 5,
        "width": 12,
        "height": 14,
        "label": "Office\nPorch",
        "color": "porch",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "11'4\" x 10'",
    },
    {
        "x": -2,
        "y": 45,
        "width": 10,
        "height": 8,
        "label": "WIC",
        "color": "closet",
        "label_fontsize": 7,
        "auto_dimension": True,
        "dimension_text": "12'",
    },
    {
        "x": -12,
        "y": 25,
        "width": 20,
        "height": 20,
        "label": "Master\nSuite",
        "color": "bedroom",
        "label_fontsize": 10,
        "auto_dimension": True,
        "dimension_text": "17'-4\" x 22'-8\"",
        "notes": "Vaulted Clg.",
    },
    {
        "x": -12,
        "y": 53,
        "width": 12,
        "height": 14,
        "label": "Master\nBath",
        "color": "bathroom",
        "label_fontsize": 9,
        "notes": "12' Clg.",
    },
    {
        "x": -4,
        "y": 53,
        "width": 12,
        "height": 14,
        "label": "WIC",
        "color": "closet",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "12'",
    },
    {
        "x": -12,
        "y": 10,
        "width": 15,
        "height": 15,
        "label": "Master\nPorch",
        "color": "porch",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "19'-2\" x 12'-6\"",
    },
    {
        "x": -27,
        "y": 10,
        "width": 15,
        "height": 15,
        "label": "Side\nPorch",
        "color": "porch",
        "label_fontsize": 8,
        "auto_dimension": True,
        "dimension_text": "10' x 22'",
    },
    {
        "x": 0,
        "y": 81,
        "width": 20,
        "height": 29,
        "label": "Front Porch",
        "color": "porch",
        "label_fontsize": 10,
        "auto_dimension": True,
        "dimension_text": "50'-5\" x 12'-4\"",
    },
]

MAIN_FLOOR_DOORS_DEFAULT = [
    {"x": 58, "y": 70, "width": 3, "direction": "down", "swing": "right"},
    {"x": 58, "y": 61, "width": 3, "direction": "down", "swing": "left"},
    {"x": 65, "y": 48, "width": 2.5, "direction": "down", "swing": "left"},
    {"x": 60, "y": 48, "width": 2.5, "direction": "down", "swing": "left"},
    {"x": 58, "y": 40, "width": 3, "direction": "down", "swing": "left"},
    {"x": 62, "y": 23, "width": 2.5, "direction": "down", "swing": "left"},
    {"x": 53, "y": 43, "width": 2.5, "direction": "down", "swing": "right"},
    {"x": 50, "y": 65, "width": 3, "direction": "down", "swing": "right"},
    {"x": 40, "y": 73, "width": 3, "direction": "down", "swing": "right"},
    {"x": 48, "y": 60, "width": 2.5, "direction": "down", "swing": "right"},
    {"x": 45, "y": 55, "width": 2.5, "direction": "down", "swing": "right"},
    {"x": 32, "y": 60, "width": 3, "direction": "down", "swing": "right"},
    {"x": 45, "y": 5, "width": 4, "direction": "down", "swing": "left"},
    {"x": 28, "y": 5, "width": 4, "direction": "down", "swing": "left"},
    {"x": 8, "y": 73, "width": 4, "direction": "down", "swing": "right"},
    {"x": 10, "y": 45, "width": 2.5, "direction": "down", "swing": "left"},
    {"x": 12, "y": 32, "width": 3, "direction": "down", "swing": "left"},
    {"x": 12, "y": 5, "width": 3, "direction": "down", "swing": "left"},
    {"x": -2, "y": 48, "width": 2.5, "direction": "down", "swing": "right"},
    {"x": 2, "y": 25, "width": 3, "direction": "down", "swing": "left"},
    {"x": -6, "y": 53, "width": 3, "direction": "down", "swing": "left"},
    {"x": -2, "y": 53, "width": 3, "direction": "down", "swing": "left"},
    {"x": -2, "y": 10, "width": 4, "direction": "down", "swing": "left"},
    {"x": 20, "y": 90, "width": 4, "direction": "left", "swing": "down"},
]

MAIN_FLOOR_WINDOWS_DEFAULT = [
    {"x": 5, "y": 81, "width": 8, "orientation": "horizontal"},
    {"x": 12, "y": 81, "width": 6, "orientation": "horizontal"},
    {"x": -12, "y": 35, "width": 8, "orientation": "vertical"},
    {"x": -2, "y": 25, "width": 6, "orientation": "horizontal"},
    {"x": 70, "y": 60, "width": 6, "orientation": "vertical"},
    {"x": 70, "y": 38, "width": 6, "orientation": "vertical"},
    {"x": 25, "y": 5, "width": 8, "orientation": "horizontal"},
    {"x": 48, "y": 19, "width": 6, "orientation": "horizontal"},
    {"x": 53, "y": 19, "width": 5, "orientation": "horizontal"},
    {"x": -12, "y": 60, "width": 6, "orientation": "vertical"},
    {"x": 20, "y": 81, "width": 6, "orientation": "horizontal"},
]

MAIN_FLOOR_FIREPLACES_DEFAULT = [
    {"x": 35, "y": 63, "width": 4, "height": 3, "label": ""},
    {"x": -4, "y": 73, "width": 3, "height": 3, "label": "Gas\nFireplace"},
]

MAIN_FLOOR_STAIRS_DEFAULT = [
    {
        "x": 20,
        "y": 45,
        "width": 12,
        "height": 6,
        "num_steps": 10,
        "orientation": "horizontal",
        "label": "DN",
    },
]


# =============================================================================
# BASEMENT DEFAULT DATA
# =============================================================================

BASEMENT_ROOMS_DEFAULT = [
    {
        "x": 0,
        "y": 0,
        "width": 10,
        "height": 30,
        "label": "Bath",
        "color": "bath",
        "label_fontsize": 9,
        "auto_dimension": True,
        "dimension_text": "30'",
    },
    {
        "x": 10,
        "y": 0,
        "width": 15,
        "height": 15,
        "label": "Utilities",
        "color": "utility",
        "label_fontsize": 7,
        "notes": "Power, Internet,\nGas, Furnace,\nWater Treatment",
    },
    {
        "x": 0,
        "y": 30,
        "width": 5,
        "height": 30,
        "label": "Books",
        "color": "books",
        "label_fontsize": 8,
    },
    {
        "x": 5,
        "y": 60,
        "width": 20,
        "height": 40,
        "label": "Gaming / Studio",
        "color": "gaming",
        "label_fontsize": 11,
        "label_color": "white",
        "auto_dimension": True,
        "dimension_text": "40' x 20'",
    },
    {
        "x": 5,
        "y": 88,
        "width": 20,
        "height": 12,
        "label": "Books",
        "color": "books",
        "label_fontsize": 8,
    },
    {
        "x": 10,
        "y": 30,
        "width": 10,
        "height": 10,
        "label": "Storage\nUnder\nStairs",
        "color": "storage",
        "label_fontsize": 7,
    },
    {
        "x": 20,
        "y": 15,
        "width": 15,
        "height": 8,
        "label": "Books",
        "color": "books",
        "label_fontsize": 8,
    },
    {
        "x": 20,
        "y": 23,
        "width": 20,
        "height": 37,
        "label": "",
        "color": "bar",
        "label_fontsize": 10,
    },
    {
        "x": 35,
        "y": 15,
        "width": 25,
        "height": 8,
        "label": "Books",
        "color": "books",
        "label_fontsize": 8,
    },
    {
        "x": 40,
        "y": 30,
        "width": 20,
        "height": 30,
        "label": "Pool\nUtilities",
        "color": "utility",
        "label_fontsize": 9,
    },
    {
        "x": 40,
        "y": 88,
        "width": 20,
        "height": 12,
        "label": "Books",
        "color": "books",
        "label_fontsize": 8,
    },
]

BASEMENT_THEATER_DEFAULT = {
    "room": {
        "x": 25,
        "y": 0,
        "width": 35,
        "height": 15,
        "label": "Home Theater",
        "color": "theater",
        "label_fontsize": 11,
        "label_color": "white",
        "fontweight": "bold",
        "auto_dimension": True,
        "dimension_text": "30' x 40'",
    },
    "seating": {
        "start_x": 28,
        "start_y": 2,
        "rows": 4,
        "seats_per_row": 3,
        "chair_width": 3,
        "chair_height": 2.5,
        "row_spacing": 5,
        "seat_spacing": 4,
        "chair_color": "chair",
        "edge_color": "gray",
    },
    "false_wall": {
        "x1": 25,
        "y1": 0,
        "x2": 60,
        "y2": 0,
        "color": "red",
        "linewidth": 4,
        "linestyle": "--",
        "label": "False Wall",
        "label_x": 42,
        "label_y": -2,
    },
}

BASEMENT_POOL_DEFAULT = {
    "area": {
        "x": 25,
        "y": 60,
        "width": 35,
        "height": 40,
        "color": "pool_area",
        "label": "Pool Area",
    },
    "pool": {
        "x": 28,
        "y": 63,
        "width": 18,
        "height": 32,
        "color": "pool",
        "edge_color": "#0288d1",
        "label": "Salt Water\nPool",
    },
    "hot_tub": {
        "x": 52,
        "y": 73,
        "radius": 4,
        "color": "spa",
        "edge_color": "#0288d1",
        "label": "Hot\nTub",
    },
    "spa_label": {
        "x": 52,
        "y": 88,
        "text": "Spa",
    },
}

BASEMENT_DOORS_DEFAULT = [
    {"x": 0, "y": 20, "width": 3, "direction": "up", "swing": "right"},
    {"x": 20, "y": 8, "width": 3, "direction": "up", "swing": "left"},
    {"x": 40, "y": 15, "width": 4, "direction": "up", "swing": "left"},
    {"x": 20, "y": 60, "width": 4, "direction": "up", "swing": "left"},
    {"x": 20, "y": 35, "width": 4, "direction": "up", "swing": "right"},
    {"x": 40, "y": 45, "width": 3, "direction": "up", "swing": "left"},
    {"x": 40, "y": 60, "width": 4, "direction": "up", "swing": "left"},
    {"x": 40, "y": 15, "width": 4, "direction": "up", "swing": "left"},
]

BASEMENT_STAIRS_DEFAULT = [
    {
        "x": 0,
        "y": 60,
        "width": 5,
        "height": 10,
        "num_steps": 8,
        "orientation": "vertical",
        "label": "Exit\nStairs\n60'",
    },
    {
        "x": 0,
        "y": 70,
        "width": 5,
        "height": 12,
        "num_steps": 8,
        "orientation": "vertical",
        "label": "Stairs\nto Main",
    },
]

BASEMENT_FURNITURE_DEFAULT = [
    {
        "furniture_type": "ellipse",
        "x": 15,
        "y": 78,
        "width": 4,
        "height": 12,
        "color": "hammock",
        "edge_color": "#8b4513",
        "label": "Hammock",
        "label_fontsize": 7,
        "rotation": 90,
        "linewidth": 2,
    },
    {
        "furniture_type": "rectangle",
        "x": 23,
        "y": 35,
        "width": 4,
        "height": 12,
        "color": "wood",
        "edge_color": "brown",
        "label": "Bar",
        "label_fontsize": 7,
        "label_color": "white",
        "rotation": 90,
        "linewidth": 2,
    },
    {
        "furniture_type": "rectangle",
        "x": 30,
        "y": 35,
        "width": 3,
        "height": 12,
        "color": "leather",
        "edge_color": "black",
        "label": "Couch",
        "label_fontsize": 6,
        "label_color": "white",
        "rotation": 90,
        "linewidth": 1,
    },
    {
        "furniture_type": "circle",
        "x": 28,
        "y": 41,
        "width": 1.5,
        "color": "wood",
        "edge_color": "black",
        "label": "",
        "linewidth": 1,
    },
    {
        "furniture_type": "rectangle",
        "x": 26,
        "y": 1,
        "width": 8,
        "height": 1.5,
        "color": "#333333",
        "edge_color": "black",
        "label": "",
        "linewidth": 1,
    },
]

BASEMENT_TEXT_ANNOTATIONS_DEFAULT = [
    {"x": 22, "y": 32, "text": "Sink\nDW", "fontsize": 6, "ha": "center"},
    {"x": 22, "y": 50, "text": "Coffee", "fontsize": 6, "ha": "center"},
    {
        "x": 30,
        "y": 56,
        "text": "Bar Area",
        "fontsize": 10,
        "ha": "center",
        "fontweight": "bold",
    },
    {
        "x": 55,
        "y": 7,
        "text": "Rows of\nChairs",
        "fontsize": 8,
        "ha": "center",
        "color": "white",
    },
]


# Export all defaults
__all__ = [
    # Main floor defaults
    "MAIN_FLOOR_ROOMS_DEFAULT",
    "MAIN_FLOOR_DOORS_DEFAULT",
    "MAIN_FLOOR_WINDOWS_DEFAULT",
    "MAIN_FLOOR_FIREPLACES_DEFAULT",
    "MAIN_FLOOR_STAIRS_DEFAULT",
    # Basement defaults
    "BASEMENT_ROOMS_DEFAULT",
    "BASEMENT_THEATER_DEFAULT",
    "BASEMENT_POOL_DEFAULT",
    "BASEMENT_DOORS_DEFAULT",
    "BASEMENT_STAIRS_DEFAULT",
    "BASEMENT_FURNITURE_DEFAULT",
    "BASEMENT_TEXT_ANNOTATIONS_DEFAULT",
]
